#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar position=top \
 height=40 \
 blur_radius=30 \
 color=$BAR_COLOR

# Default values

default=(
padding_left=5
padding_right=5
icon.font="SF Pro:Semibold:14.0"
label.font="SF Pro:Semibold:14.0"
icon.color=$WHITE
label.color=$WHITE
icon.padding_left=10
icon.padding_right=4
label.padding_left=4
label.padding_right=10
background.color=$ITEM_BG_COLOR
background.corner_radius=5
background.height=24
)
sketchybar --default "${default[@]}"

# Left items

source "$ITEM_DIR/aerospace.sh"
source $ITEM_DIR/front_app.sh

# Right items

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

# Finalize

sketchybar --update
